### ISSUE TITLE
Package in PyPI

### ISSUE THREAD

**Issue by thomascaillier** [SoftGorilla/restheart-python-client#1]
Hello,

First of all, thanks for this efficient tool 👍 

I suggest to push this package in PyPI, as we would be able to use it using `pip`. [Here is a great tutorial](https://www.freecodecamp.org/news/how-to-create-and-upload-your-first-python-package-to-pypi/).

**Comment by AlonEirew** [comment]
Hi @thomascaillier, 

Thank you for this feedback. 
I'm no longer maintaining this repo, if you would be willing to contribute and make it public in PyPI, it will be great. 

Thanks,
Alon.
